package com.books.model;

// Generated 17 déc. 2014 18:17:49 by Hibernate Tools 3.4.0.CR1

/**
 * Books generated by hbm2java
 */
public class Books implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7345401874970693833L;
	private String isbn;
	private String titre;
	private String auteur;
	private String genre;

	public Books() {
	}

	public Books(String isbn) {
		this.isbn = isbn;
	}

	public Books(String isbn, String titre, String auteur, String genre) {
		this.isbn = isbn;
		this.titre = titre;
		this.auteur = auteur;
		this.genre = genre;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getAuteur() {
		return this.auteur;
	}

	public void setAuteur(String auteur) {
		this.auteur = auteur;
	}

	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

}
