package com.books.model;

// Generated 14 janv. 2015 16:30:53 by Hibernate Tools 3.4.0.CR1

/**
 * Tmatch generated by hbm2java
 */
public class Tmatch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3147747264817683802L;
	private Integer num;
	private String user;
	private String book;
	private String closestuser;
	private String farthestuser;

	public Tmatch() {
	}

	public Tmatch(String user, String book, String closestuser,
			String farthestuser) {
		this.user = user;
		this.book = book;
		this.closestuser = closestuser;
		this.farthestuser = farthestuser;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getBook() {
		return this.book;
	}

	public void setBook(String book) {
		this.book = book;
	}

	public String getClosestuser() {
		return this.closestuser;
	}

	public void setClosestuser(String closestuser) {
		this.closestuser = closestuser;
	}

	public String getFarthestuser() {
		return this.farthestuser;
	}

	public void setFarthestuser(String farthestuser) {
		this.farthestuser = farthestuser;
	}

}
