package com.books.model;

// Generated 17 déc. 2014 18:17:49 by Hibernate Tools 3.4.0.CR1

/**
 * Tmatch generated by hbm2java
 */
public class Tmatch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7782753510331438517L;
	private Integer num;
	private Integer eval1;
	private Integer eval2;
	private String catMatch;

	public Tmatch() {
	}

	public Tmatch(Integer eval1, Integer eval2, String catMatch) {
		this.eval1 = eval1;
		this.eval2 = eval2;
		this.catMatch = catMatch;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public Integer getEval1() {
		return this.eval1;
	}

	public void setEval1(Integer eval1) {
		this.eval1 = eval1;
	}

	public Integer getEval2() {
		return this.eval2;
	}

	public void setEval2(Integer eval2) {
		this.eval2 = eval2;
	}

	public String getCatMatch() {
		return this.catMatch;
	}

	public void setCatMatch(String catMatch) {
		this.catMatch = catMatch;
	}

}
