package com.books.model;

// Generated 7 janv. 2015 16:18:41 by Hibernate Tools 3.4.0.CR1

/**
 * Tmatch generated by hbm2java
 */
public class Tmatch implements java.io.Serializable {

	private Integer num;
	private String user1;
	private String user2;
	private String book;
	private Boolean closest;

	public Tmatch() {
	}

	public Tmatch(String user1, String user2, String book, Boolean closest) {
		this.user1 = user1;
		this.user2 = user2;
		this.book = book;
		this.closest = closest;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public String getUser1() {
		return this.user1;
	}

	public void setUser1(String user1) {
		this.user1 = user1;
	}

	public String getUser2() {
		return this.user2;
	}

	public void setUser2(String user2) {
		this.user2 = user2;
	}

	public String getBook() {
		return this.book;
	}

	public void setBook(String book) {
		this.book = book;
	}

	public Boolean getClosest() {
		return this.closest;
	}

	public void setClosest(Boolean closest) {
		this.closest = closest;
	}

}
