package com.books.model;

// Generated 17 déc. 2014 18:17:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3183763185477386593L;
	private String email;
	private String name;
	private String pwd;
	private String address;
	private String tel;
	private Date creationDate;
	private Boolean accountStatus;
	private Boolean isAdmin;

	public User() {
	}

	public User(String email) {
		this.email = email;
	}

	public User(String email, String name, String pwd, String address,
			String tel, Date creationDate, Boolean accountStatus,
			Boolean isAdmin) {
		this.email = email;
		this.name = name;
		this.pwd = pwd;
		this.address = address;
		this.tel = tel;
		this.creationDate = creationDate;
		this.accountStatus = accountStatus;
		this.isAdmin = isAdmin;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Boolean getAccountStatus() {
		return this.accountStatus;
	}

	public void setAccountStatus(Boolean accountStatus) {
		this.accountStatus = accountStatus;
	}

	public Boolean getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(Boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

}
